tables:
  todos:
    fields:
      - id:
          type: serial
          unique: true
          not_null: true
      - text:
          type: text
          unique: true
          not_null: true
      - completed:
          type: bool
          unique: false
          not_null: true
    primary_keys:
      - id
  users:
    fields:
      - id:
          type: serial
          unique: true
          not_null: true
      - email:
          type: text
          unique: true
          not_null: true
      - username:
          type: text
          unique: false
          not_null: false
      - gender:
          type: text
          unique: false
          not_null: false
    primary_keys:
      - id

types:
  - name: Todo
    ref: todos
    fields:
      - name: text
        type: String
        required: true
      - name: completed
        type: Boolean
        required: false
  - name: User
    ref: users
    fields:
      - name: email
        type: String
        required: true
      - name: username
        type: String
        required: false
      - name: gender
        type: String
        required: false

