todos:
  fields:
    - id:
        type: serial
        unique: true
        not_null: true
    - text:
        type: text
        unique: true
        not_null: true
    - completed:
        type: bool
        unique: false
        not_null: true
  primary_keys:
    - id
